/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ifp.centrodefauna;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajpyu
 */
public class PanelTratamiento extends javax.swing.JPanel {

    /**
     * Creates new form PanelTratamiento
     */
    private int indice = -1;

    public PanelTratamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jButtonBucar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();
        jLabelMedicamento = new javax.swing.JLabel();
        jTextFieldMed = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPresc = new javax.swing.JTextArea();
        jLabelPrescripcion = new javax.swing.JLabel();
        jButtonAddMed = new javax.swing.JButton();
        jLabelPrescripcion1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaProc = new javax.swing.JTextArea();
        jButtonAddProc = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableMeds = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableProc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 251, 244));
        setMaximumSize(new java.awt.Dimension(803, 564));
        setMinimumSize(new java.awt.Dimension(803, 564));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(75, 134, 115));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Tratamiento");
        Titulo.setToolTipText("");
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(75, 134, 115));
        jLabelNombre.setText("Nombre del paciente:");

        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });

        jButtonBucar.setBackground(new java.awt.Color(245, 223, 153));
        jButtonBucar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonBucar.setForeground(new java.awt.Color(75, 134, 115));
        jButtonBucar.setText("Buscar");
        jButtonBucar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonBucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBucarActionPerformed(evt);
            }
        });

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clase Animal", "Nombre", "Especie", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLista);
        if (jTableLista.getColumnModel().getColumnCount() > 0) {
            jTableLista.getColumnModel().getColumn(0).setResizable(false);
            jTableLista.getColumnModel().getColumn(0).setPreferredWidth(12);
            jTableLista.getColumnModel().getColumn(1).setResizable(false);
            jTableLista.getColumnModel().getColumn(2).setResizable(false);
            jTableLista.getColumnModel().getColumn(2).setPreferredWidth(12);
            jTableLista.getColumnModel().getColumn(3).setResizable(false);
            jTableLista.getColumnModel().getColumn(3).setPreferredWidth(5);
        }

        jLabelMedicamento.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelMedicamento.setForeground(new java.awt.Color(75, 134, 115));
        jLabelMedicamento.setText("Medicamento:");

        jTextFieldMed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMedKeyTyped(evt);
            }
        });

        jTextAreaPresc.setColumns(20);
        jTextAreaPresc.setRows(5);
        jTextAreaPresc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaProcKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaPresc);

        jLabelPrescripcion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelPrescripcion.setForeground(new java.awt.Color(75, 134, 115));
        jLabelPrescripcion.setText("Prescripción:");

        jButtonAddMed.setBackground(new java.awt.Color(245, 223, 153));
        jButtonAddMed.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonAddMed.setForeground(new java.awt.Color(75, 134, 115));
        jButtonAddMed.setText("Añadir");
        jButtonAddMed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMedActionPerformed(evt);
            }
        });

        jLabelPrescripcion1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelPrescripcion1.setForeground(new java.awt.Color(75, 134, 115));
        jLabelPrescripcion1.setText("Procedimiento:");

        jTextAreaProc.setColumns(20);
        jTextAreaProc.setRows(3);
        jTextAreaProc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaProcKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jTextAreaProc);

        jButtonAddProc.setBackground(new java.awt.Color(245, 223, 153));
        jButtonAddProc.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonAddProc.setForeground(new java.awt.Color(75, 134, 115));
        jButtonAddProc.setText("Añadir");
        jButtonAddProc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAddProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProcActionPerformed(evt);
            }
        });

        jTableMeds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicamento", "Prescripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableMeds);
        if (jTableMeds.getColumnModel().getColumnCount() > 0) {
            jTableMeds.getColumnModel().getColumn(0).setResizable(false);
            jTableMeds.getColumnModel().getColumn(1).setResizable(false);
            jTableMeds.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        jTableProc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Procedimientos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableProc);
        if (jTableProc.getColumnModel().getColumnCount() > 0) {
            jTableProc.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("*Campos vacíos");
        jLabel1.setVisible(false);

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("*Campo vacío");
        jLabel2.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonAddMed))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelMedicamento)
                                            .addGap(27, 27, 27)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldMed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabelPrescripcion, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBucar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonAddProc))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelPrescripcion1)))
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBucar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddMed)
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPrescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddProc)
                            .addComponent(jLabel2)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBucarActionPerformed
        DefaultTableModel modeloPaciente = (DefaultTableModel) jTableLista.getModel();
        modeloPaciente.setRowCount(0);

        indice = -1;

        for (Animal a : CentroDeFauna.listadoAnimales) {
            indice++;
            if (a.getNombre().equalsIgnoreCase(jTextNombre.getText())) {
                Object[] fila = new Object[4];
                fila[0] = a.getTipo();
                fila[1] = a.getNombre();
                fila[2] = a.getEspecie();
                fila[3] = a.getPeso();
                modeloPaciente.addRow(fila);
                break;
            }
        }
        if (CentroDeFauna.listadoAnimales.get(indice).getTratamiento() == null) {
            CentroDeFauna.listadoAnimales.get(indice).setTratamiento(new Tratamiento());
        }

        actualizarMedicamentos();
        actualizarProcs();
    }//GEN-LAST:event_jButtonBucarActionPerformed

    private void jButtonAddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMedActionPerformed
        if (!jTextFieldMed.getText().isEmpty()) {
            jLabel1.setVisible(false);
            Medicamento m = new Medicamento();
            m.setMedicamento(jTextFieldMed.getText());
            if (jTextAreaPresc.getText().isEmpty()) {
                m.setPrescripcion("");
            } else {
                m.setPrescripcion(jTextAreaPresc.getText());
            }
            CentroDeFauna.listadoAnimales.get(indice).getTratamiento().addMedicamento(m);
            actualizarMedicamentos();
        } else {
            jLabel1.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAddMedActionPerformed

    private void jButtonAddProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProcActionPerformed
        if (!jTextAreaProc.getText().isEmpty()) {
            jLabel2.setVisible(false);
            CentroDeFauna.listadoAnimales.get(indice).getTratamiento().addProcedimiento(jTextAreaProc.getText());
            actualizarProcs();
        } else {
            jLabel2.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAddProcActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        Gestor.IntroLetras(evt);
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextFieldMedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMedKeyTyped
        Gestor.IntroLetras(evt);
    }//GEN-LAST:event_jTextFieldMedKeyTyped

    private void jTextAreaProcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaProcKeyTyped
        Gestor.IntroLetras(evt);
    }//GEN-LAST:event_jTextAreaProcKeyTyped

    private void actualizarMedicamentos() {
        DefaultTableModel modeloMeds = (DefaultTableModel) jTableMeds.getModel();
        if (!CentroDeFauna.listadoAnimales.get(indice).getTratamiento().getMedicamentos().isEmpty()) {
            modeloMeds.setRowCount(0);
            for (Medicamento m : CentroDeFauna.listadoAnimales.get(indice).getTratamiento().getMedicamentos()) {
                Object[] fila = new Object[2];
                fila[0] = m.getMedicamento();
                fila[1] = m.getPrescripcion();
                modeloMeds.addRow(fila);
            }
        } else {
            jTableMeds.setModel(new DefaultTableModel(null, new String[]{"Medicamentos", "Prescripción"}));
        }
    }

    private void actualizarProcs() {
        DefaultTableModel modeloProcs = (DefaultTableModel) jTableProc.getModel();
        if (!CentroDeFauna.listadoAnimales.get(indice).getTratamiento().getProcedimientos().isEmpty()) {
            modeloProcs.setRowCount(0);
            for (String p : CentroDeFauna.listadoAnimales.get(indice).getTratamiento().getProcedimientos()) {
                Object[] fila = new Object[1];
                fila[0] = p;
                modeloProcs.addRow(fila);
            }
        } else {
            jTableProc.setModel(new DefaultTableModel(null, new String[]{"Procedimientos"}));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonAddMed;
    private javax.swing.JButton jButtonAddProc;
    private javax.swing.JButton jButtonBucar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMedicamento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrescripcion;
    private javax.swing.JLabel jLabelPrescripcion1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableLista;
    private javax.swing.JTable jTableMeds;
    private javax.swing.JTable jTableProc;
    private javax.swing.JTextArea jTextAreaPresc;
    private javax.swing.JTextArea jTextAreaProc;
    private javax.swing.JTextField jTextFieldMed;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
