/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ifp.centrodefauna;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajpyu
 */
public class PanelLiberacion extends javax.swing.JPanel {

    /**
     * Creates new form PanelLiberacion
     */
    private int indice;
    private Date date;

    public PanelLiberacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jButtonBucar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelRazon = new javax.swing.JLabel();
        jLabelFecha1 = new javax.swing.JLabel();
        jTextFieldVet = new javax.swing.JTextField();
        jButtonConfir = new javax.swing.JButton();
        jLabelLiberado = new javax.swing.JLabel();
        jLabelFallecido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(246, 251, 244));
        setForeground(new java.awt.Color(75, 134, 115));
        setMaximumSize(new java.awt.Dimension(417, 564));
        setMinimumSize(new java.awt.Dimension(417, 564));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(75, 134, 115));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Liberación");
        Titulo.setToolTipText("");
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(75, 134, 115));
        jLabelNombre.setText("Nombre del paciente:");

        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });

        jButtonBucar.setBackground(new java.awt.Color(245, 223, 153));
        jButtonBucar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonBucar.setForeground(new java.awt.Color(75, 134, 115));
        jButtonBucar.setText("Buscar");
        jButtonBucar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonBucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBucarActionPerformed(evt);
            }
        });

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clase Animal", "Nombre", "Especie", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLista);

        jLabelFecha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(75, 134, 115));
        jLabelFecha.setText("Fecha:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jLabelRazon.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelRazon.setForeground(new java.awt.Color(75, 134, 115));
        jLabelRazon.setText("Detalles:");

        jLabelFecha1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelFecha1.setForeground(new java.awt.Color(75, 134, 115));
        jLabelFecha1.setText("Veterinario:");

        jTextFieldVet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });

        jButtonConfir.setBackground(new java.awt.Color(245, 223, 153));
        jButtonConfir.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonConfir.setForeground(new java.awt.Color(75, 134, 115));
        jButtonConfir.setText("Confirmar");
        jButtonConfir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirActionPerformed(evt);
            }
        });

        jLabelLiberado.setForeground(new java.awt.Color(51, 51, 255));
        jLabelLiberado.setText("*Este paciente ya ha sido liberado");
        jLabelLiberado.setVisible(false);

        jLabelFallecido.setForeground(new java.awt.Color(51, 51, 255));
        jLabelFallecido.setText("*Este paciente ha fallecido");
        jLabelFallecido.setVisible(false);

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("*Campos vacíos");
        jLabel2.setVisible(false);

        jButton1.setText("🔄️");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldVet, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFallecido)
                            .addComponent(jLabelLiberado))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBucar)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBucar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConfir)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLiberado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFallecido)))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBucarActionPerformed
        DefaultTableModel modeloPaciente = (DefaultTableModel) jTableLista.getModel();
        modeloPaciente.setRowCount(0);

        indice = -1;

        for (Animal a : CentroDeFauna.listadoAnimales) {
            indice++;
            if (a.getNombre().equalsIgnoreCase(jTextNombre.getText())) {
                Object[] fila = new Object[4];
                fila[0] = a.getTipo();
                fila[1] = a.getNombre();
                fila[2] = a.getEspecie();
                fila[3] = a.getPeso();
                modeloPaciente.addRow(fila);
                break;
            }
        }

        if (CentroDeFauna.listadoAnimales.get(indice).getMuerte() == null) {
            if (CentroDeFauna.listadoAnimales.get(indice).getLiberacion() != null) {
                jLabelLiberado.setVisible(true);
                jButtonConfir.setEnabled(false);
            } else {
                jLabelLiberado.setVisible(false);
                jLabelFallecido.setVisible(false);
                jButtonConfir.setEnabled(true);
            }
        } else {
            jLabelFallecido.setVisible(true);
            jButtonConfir.setEnabled(false);
        }
        jTextArea1.setText("");
        jTextFieldVet.setText("");
    }//GEN-LAST:event_jButtonBucarActionPerformed

    private void jButtonConfirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirActionPerformed
        if (indice != -1) {
            if (!jTextFieldVet.getText().isEmpty() && !jTextArea1.getText().isEmpty()) {
                Liberacion l = new Liberacion(jTextArea1.getText(), date, jTextFieldVet.getText());
                CentroDeFauna.listadoAnimales.get(indice).setLiberacion(l);
                jButtonConfir.setEnabled(false);
            } else {
                jLabel2.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonConfirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.InitFecha();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        Gestor.IntroLetras(evt);
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        Gestor.IntroLetras(evt);
    }//GEN-LAST:event_jTextArea1KeyTyped

    public void InitFecha() {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        date = new Date();
        jTextFieldFecha.setText(formato.format(date));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBucar;
    private javax.swing.JButton jButtonConfir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFallecido;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFecha1;
    private javax.swing.JLabel jLabelLiberado;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRazon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLista;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldVet;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
